name = "Perseus S2"
author = "sans9536, minecraftbossdj"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dd8c1bfcceaf589ba465587d6333b99648b03a96e57fdee5dfaf939ee675971"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
